# Generated by Django 3.2.1 on 2021-06-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_cart_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
