# Generated by Django 3.2.1 on 2021-05-08 05:06

import app.models
import cpf_field.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('endereco', models.CharField(max_length=50, verbose_name='endereco')),
                ('cpf', cpf_field.models.CPFField(max_length=14)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro Equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', app.models.ClienteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('id_tamanho', models.AutoField(primary_key=True, serialize=False, verbose_name='id_bolo')),
                ('sem_glutem', models.IntegerField(verbose_name='glutem')),
                ('sem_lactose', models.IntegerField(verbose_name='lactose')),
                ('valor_bolo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor_bolo')),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id_cobertura', models.AutoField(primary_key=True, serialize=False, verbose_name='cobertura_id')),
                ('nome_cobertura', models.CharField(max_length=50, verbose_name='nome_cobertura')),
                ('descricao_cobertura', models.CharField(max_length=250, verbose_name='descricao_cobertura')),
                ('sem_glutem', models.IntegerField(verbose_name='glutem')),
                ('sem_lactose', models.IntegerField(verbose_name='lactose')),
                ('valor_cobertura', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor_cobertura')),
            ],
        ),
        migrations.CreateModel(
            name='Massa',
            fields=[
                ('id_massa', models.AutoField(primary_key=True, serialize=False, verbose_name='id_massa')),
                ('nome_massa', models.CharField(max_length=50, verbose_name='nome_massa')),
                ('descricao_massa', models.CharField(max_length=250, verbose_name='descricao')),
                ('sem_glutem', models.IntegerField(verbose_name='glutem')),
                ('sem_lactose', models.IntegerField(verbose_name='lactose')),
                ('valor_massa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor_massa')),
            ],
        ),
        migrations.CreateModel(
            name='Recheio',
            fields=[
                ('id_recheio', models.AutoField(primary_key=True, serialize=False, verbose_name='id_recheio')),
                ('nome_recheio', models.CharField(max_length=50, verbose_name='nome_recheio')),
                ('descricao_recheio', models.CharField(max_length=250, verbose_name='descricao_recheio')),
                ('sem_glutem', models.IntegerField(verbose_name='glutem')),
                ('sem_lactose', models.IntegerField(verbose_name='lactose')),
                ('valor_recheio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor_recheio')),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id_tamanho', models.AutoField(primary_key=True, serialize=False, verbose_name='Tamanho')),
                ('nome_tamanho', models.CharField(max_length=50, verbose_name='nome_tamanho')),
                ('valor_tamanho', models.FloatField(max_length=20, verbose_name='valor_tamanho')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id_topping', models.AutoField(primary_key=True, serialize=False, verbose_name='íd_topping')),
                ('nome_topping', models.CharField(max_length=50, verbose_name='nome_topping')),
                ('descricao_topping', models.CharField(max_length=250, verbose_name='descricao_topping')),
                ('valor_topping', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor_topping')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, verbose_name='id_pedido')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='desconto')),
                ('data_hora_pedido', models.DateTimeField(verbose_name='data_pedido')),
                ('data_hora_pedido_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='data_finalizado')),
                ('data_hora_pedido_retirado', models.DateTimeField(blank=True, null=True, verbose_name='data_retirado')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor_total')),
                ('bolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolo', verbose_name='Bolo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='bolo',
            name='bolo_cobertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cobertura', verbose_name='Bolo_cobertura'),
        ),
        migrations.AddField(
            model_name='bolo',
            name='bolo_massa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.massa', verbose_name='Boloc_Massa'),
        ),
        migrations.AddField(
            model_name='bolo',
            name='bolo_recheio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recheio', verbose_name='Bolo_Recheio'),
        ),
        migrations.AddField(
            model_name='bolo',
            name='bolo_tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tamanho', verbose_name='Bolo_Tamanho'),
        ),
        migrations.AddField(
            model_name='bolo',
            name='bolo_topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topping', verbose_name='Bolo_Topping'),
        ),
    ]
