# Generated by Django 3.1.7 on 2021-04-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recheio',
            fields=[
                ('id_recheio', models.AutoField(primary_key=True, serialize=False)),
                ('nome_recheio', models.CharField(max_length=50)),
                ('descricao_recheio', models.CharField(max_length=250)),
            ],
        ),
    ]
