# Generated by Django 3.2.1 on 2021-06-17 01:57

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, null=True),
        ),
    ]
