# Generated by Django 3.2.1 on 2021-06-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cliente_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
