# Generated by Django 3.2 on 2021-05-22 13:34

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, upload_to='produtos', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Massa', 'Massa'), ('Cobertura', 'Cobertura'), ('Recheio', 'Recheio'), ('Tamanho', 'Tamanho'), ('Topping', 'Topping')], max_length=9),
        ),
    ]
