# Generated by Django 3.2.1 on 2021-06-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
