# Generated by Django 3.2 on 2021-05-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210522_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('produto_id', models.IntegerField(blank=True, null=True)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                
            ],
        ),
    ]
