# Generated by Django 3.2.1 on 2021-06-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cart_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_confirm',
        ),
    ]
